
spring.thymeleaf.cache: false
spring.thymeleaf.mode: HTML

spring:
  application:
    name: camaaloth-uploader
  threads:
    virtual:
      enabled: true
  jackson:
    date-format:
    serialization:
      write-date-keys-as-timestamps: false